### ISSUE TITLE
MouseMotion event returns absolute instead of relative values, when running Linux in a VM

### ISSUE THREAD

**Issue by iceiix** [rust-windowing/glutin#1084]
I'm listening for `glutin::DeviceEvent::MouseMotion{delta:(xrel, yrel)}` and it works fine on most systems, but Ubuntu 18.04.1 in VMware Fusion causes `xrel` and `yrel` to be set to large absolute values as the mouse moves, for example:

MouseMotion 39128.40293884277 25325.613555908203
MouseMotion 39128.40293884277 25371.612854003906
MouseMotion 39128.40293884277 25416.6121673584

instead of the expected relative delta values. When implementing mouse look in a game using this event, this causes the player to rapidly spin instead of look where their mouse is pointing. SDL2 has similar issues: https://bugzilla.libsdl.org/show_bug.cgi?id=2150 https://bugzilla.libsdl.org/show_bug.cgi?id=2954 https://stackoverflow.com/questions/25576438/sdl-getrelativemousestate-strange-behaviour, but there is an option to enable a "relative mode warp" hint in SDL2, does/could Glutin have something similar?

**Comment by francesca64** [comment]
For future reference, this issue relates to code in [winit](https://github.com/tomaka/winit), which glutin depends on.

> does/could Glutin have something similar?

We currently don't, but if the aforementioned fix in SDL works fine, then it shouldn't be hard to make a similar fix here. Relevant code: https://github.com/spurious/SDL-mirror/blob/d3d9a9ddd00f710835a3c133d6c196b7c4bd1792/src/events/SDL_mouse.c#L302

It would be awesome if you'd like to try making a PR for this to winit, since it could take a bit of time before I'll be able to get to it (and I won't be able to repro/test this myself).

**Comment by ZeGentzy** [comment]
Closing in favor of upstream. https://github.com/rust-windowing/winit/issues/876
