### ISSUE TITLE
Headless with independent eventsloop

### ISSUE THREAD

**Issue by msiglreith** [rust-windowing/glutin#1152]
I'm trying to create a 'true' headless context (no present or event polling at all) along a shared windowed context. Therefore I would like to create an own eventloop for these independent of the windowed context. The docs state:

> One notable limitation of the Wayland backend when it comes to shared Contexts is that both contexts must use the same events loop.

Is there further information which parts prevent this? Or what would be the issue when violation this limitation?

**Comment by ZeGentzy** [comment]
You will get an `EGL_BAD_MATCH` error.

Egl specs, §3.7.1.6:

> An EGL_BAD_MATCH error is generated if an OpenGL or OpenGL ES context is requested and any of:
> [..]
>    - share context was created on a different display than the one
referenced by config 

With Wayland, different connections to Wayland result in a different EGL display. I cannot recall the details. This is not the case with X11, because they all get the same connection.

Depending on how you interpret the specs, you could argue that this is a bug in the mesa* impl of context sharing.

*If I remember correctly, this wasn't caused by mesa, but instead by libglvnd.so or something of that likes. The details are fuzzy now.

**Comment by msiglreith** [comment]
I looked a bit into this and it appears that mesa doesn't currently allow sharing across different displays as you mentioned. I haven't looked how deep this is rooted in the driver.

**Comment by kchibisov** [comment]
Not relevant after #1439.
