### ISSUE TITLE
Servo on Windows is unresponsive with 0.21

### ISSUE THREAD

**Issue by jdm** [rust-windowing/glutin#1163]
A regression was introduced somewhere between 0.20 and 0.21 that makes Servo on Windows 10 rapidly change window sizes at startup and remain unresponsive to input once the window settles. I'm going to attempt to identify the responsible changeset.

**Comment by jdm** [comment]
The change in behaviour appears in 90f0ef412bb9577.

**Comment by jdm** [comment]
The same behaviour is observed if we use WGL or EGL via ANGLE.

**Comment by ZeGentzy** [comment]
@jdm can you bisect these commits: https://github.com/rust-windowing/glutin/pull/1129/commits

For some reason, PRs get squashed when merged which bugs me. Narrowing it down would be helpful.

**Comment by jdm** [comment]
86f888a548f9ec2ef777089687506d7fa1f78ecf is the first commit in that series that allows the build to complete on windows, and it exhibits the problem.

**Comment by jdm** [comment]
No smoking guns yet that I can see. https://github.com/servo/servo/pull/23457/commits/17582073935c2efc677769a1e29602b334610287 and https://github.com/servo/servo/pull/23457/commits/53bb2e8743e6bf1c2219bb3fdc662c7ba63a842c are the changes in Servo that were made to accommodate the new API changes.

**Comment by ZeGentzy** [comment]
You said this happens with both EGL and WGL. This is the only change to WGL: https://github.com/rust-windowing/glutin/pull/1129/files/86f888a548f9ec2ef777089687506d7fa1f78ecf?file-filters%5B%5D=.md&file-filters%5B%5D=.rs&file-filters%5B%5D=.toml&hide-deleted-files=true&owned-by%5B%5D=#diff-4823aa63e8e9d40606714e4d284a7763R200

EGL had some more changes, but mostly they were reordering of stuff. Since this is also reproduceable with WGL, I think it's safe to say it's a servo bug.

Nevertheless, this code is wrong: https://github.com/servo/servo/commit/53bb2e8743e6bf1c2219bb3fdc662c7ba63a842c#diff-ce63ad5a65d53e183963a570463a338fR444

`resize` != `set_inner_size`. `resize` operates on the context (which is a no-op on windows AFAIK), `set_inner_size` on the window. What's happening I think, is that when the window is resized, your resizing it again, and again and again. The old code resized the context itself.

https://docs.rs/glutin/0.21.0/glutin/struct.ContextWrapper.html#method.resize
https://docs.rs/glutin/0.21.0/glutin/struct.Window.html#method.set_inner_size

It should be noted that I believe winit issues one resize event at the start because of HIDPI reasons. So the user doesn't need to resize the window for this resize loop to start.

**Comment by ZeGentzy** [comment]
I think this is just more proof that `resize` needs a better name. Alas, I have yet to think of one.

**Comment by jdm** [comment]
Totally believable. Thanks for the investigation; I'll try adjusting that code and report back.

**Comment by jdm** [comment]
The window resizing issues do indeed go away if we don't call set_inner_size. Thanks for pointing that out.
