### ISSUE TITLE
EventLoop 2.0 for Android

### ISSUE THREAD

**Issue by goddessfreya** [rust-windowing/glutin#1172]
Waiting on https://github.com/rust-windowing/winit/issues/948, to quote:

> This issue tracks the implementation of the EventLoop 2.0 rework on Android.
> 
> **Winit does not currently have any contributors able to implement this. If you are interested in Winit functioning on Android, please consider implementing this.**

**Comment by MarijnS95** [comment]
This is coming up time and time again as users try to fix the compiler errors when targeting Android. As I've written in https://github.com/rust-windowing/glutin/pull/1398 we'll need to figure out how to deal with the `Suspended` and `Resumed` events since newer `winit` doesn't have `set_suspend_callback()` anymore.

For the time being users can handle the events themselves and recreate the `glutin` context as I've done in [this Android example](https://github.com/MarijnS95/glutin/commits/wr), but this is expensive as only the surface has to be recreated. It doesn't seem to be too much effort to detach the surface from the context and dynamically add/remove it later. Then, for the user-facing side of it we can either:

1. Give users the ability to "call in" the `Suspended` and `Resumed` events manually;
2. Provide a single `handle_events()` function that users should call at the top of their `run()` closure, so that we can `match` on the `event` and perform the necessary steps there;
3. Re-wrap `winit`'s `EventLoop` and catch the events that way - we're reexporting it to the user anyway (this may be a significant implementation hurdle).

**Comment by kchibisov** [comment]
There're no winit in glutin anymore.
