### ISSUE TITLE
NoAvailablePixelFormat for AMD RX 5700

### ISSUE THREAD

**Issue by IgrauBezRuk** [rust-windowing/glutin#1220]
Hey! Faced with NoAvailablePixelFormat  on my new machine with

GPU: AMD Radeon RX 5700
Driver version 19.9.2
Windows 10
CPU: AMD Ryzen 9 3900X 12-Core

BUT! Accidently I've enabled `.with_srgb(true)` and thats worked. 
Just checked inside glutin `GlAttributes` default value is false.

**Comment by ZeGentzy** [comment]
https://github.com/rust-windowing/glutin#common-issues

**Comment by ZeGentzy** [comment]
Oh wow, even the exact same gpu... 

Afraid there is nothing that can be done. Either use a srgb surface, or a floating point surface.

**Comment by IgrauBezRuk** [comment]
I didn't get it fully. Is it really OpenGL and this exact AMD gpu limitations??) Looks weird in 2019.

**Comment by ZeGentzy** [comment]
Previously, before https://github.com/rust-windowing/glutin/pull/1179, if you requested a non-srgb surface w/ wgl, glutin would give you one  with srgb-support anyways, ignoring your request.

Upon changing it so that glutin respects your request, it was discovered that AMD gpus don't support surfaces without both floating-point formats and srgb support. There is really nothing more to it.

**Comment by IgrauBezRuk** [comment]
@ZeGentzy  Thank you)
