### ISSUE TITLE
iOS example is not working

### ISSUE THREAD

**Issue by Nazariglez** [rust-windowing/glutin#1276]
Hi! I was trying to see how glutin and opengl work on iOS (using a device). You can build and run the application, even get the event's log. But the triangle is not drawn on the screen.  The code seems to work if you execute it just with cargo run. 

Any clue about how can I solve this?. Thanks

**Comment by simlay** [comment]
Have you seen the [ios example directory](https://github.com/rust-windowing/glutin/tree/master/glutin_examples/ios-example)? It's not perfect but does stuff. Depending on the version of macOS and what SDKs, you've got available, so you might have to change the iPhone version, I had to change mine to`xcrun xcodebuild -scheme GlutinExample -project GlutinExample.xcodeproj/ -configuration Debug -destination 'platform=iOS Simulator,name=iPhone 11 Pro,OS=13.3' -derivedDataPath build` to make it work.

Also, it doesn't run the triangle example because I also couldn't get that to work. It simply [changes the background color based on tap](https://github.com/rust-windowing/glutin/blob/9283ab5c393381dce06bf46acae9d380ad1ee11f/glutin_examples/ios-example/rust/src/lib.rs#L37).

**Comment by slmjkdbtl** [comment]
@simlay You also can't get triangle to draw on screen? I've been trying to get my engine (glutin + glow) woking on iOS and I also can get background color working but can't get anything else with vertex data to draw. I wonder if anyone has succeeded

**Comment by kchibisov** [comment]
No ios support for now.

**Comment by Nazariglez** [comment]
Hey @kchibisov can you give us a hint of what's missing? We may be able to help with it.

**Comment by kchibisov** [comment]
See the new traits and for example macOS backend to understand how to impl it.
