### ISSUE TITLE
How do I cap fps?

### ISSUE THREAD

**Issue by arenacraftwow** [rust-windowing/glutin#1325]
Glutin version: `0.24`
Platform: `Linux/x11`
Details: `Up to date arch linux install on the i3 window manager without any compositors`

Hi, I'm struggling a bit to get FPS control to work. I would appreciate some help and suggest documenting the recommended pattern since I'm probably not the first one. 

Here is what I'm trying to do

```rust
fn main() {
    let event_loop = EventLoop::new();

    let gl_window: Rc<ContextWrapper<PossiblyCurrent, Window>> = {
        let window_builder = WindowBuilder::new()
            .with_title("Example");
        let context_builder = ContextBuilder::new()
            .build_windowed(window_builder, &event_loop)
            .unwrap();
        let window = unsafe {
            context_builder.make_current().unwrap()
        };
        Rc::from(window)
    };

    let mut renderer = Renderer::new();

    event_loop.run(move |event_loop_event, _, ctrl_flow| {
        *ctrl_flow = ControlFlow::Poll;

        match event_loop_event {
            Event::WindowEvent { event: window_event, .. } => {
                match window_event {
                    WindowEvent::CloseRequested => {
                        *ctrl_flow = ControlFlow::Exit;
                        return;
                    }
                    WindowEvent::Resized(_) =>{}
                    _ => {}
                };
            }
            Event::RedrawRequested(_) => {}
            Event::DeviceEvent { .. } => {}
            _ => {}
        };

        renderer.call();
    })
}


struct Renderer {
    last_rendered_at: Instant,
    render_each: Duration,
}

impl Renderer {
    pub fn new() -> Self {
        Renderer {
            last_rendered_at: Instant::now(),
            render_each: Duration::from_millis(16), // ~60 fps
        }
    }

    pub fn call(&mut self) {
        let elapsed = self.last_rendered_at.elapsed();
        if elapsed > self.render_each {
            println!("elapsed: {:?}", elapsed);
            self.last_rendered_at = Instant::now();
            self._render();
        }
    }

    fn _render(&self) {
        let mut rng = rand::thread_rng();
        // works fine with this
        thread::sleep_ms(rng.gen_range(1, 6)); 
        
        // however if rendering takes longer than our fps we get issues described below in the issue
        // thread::sleep_ms(rng.gen_range(21, 32)); 
    }
}


```

This approach _kinda_ works. Problems start when the rendering functions can't keep up with the target FPS. When that happens, closing the applications no longer works (it's like the even loop get's clogged up or something).  I also used different approaches like using `WaitUntil(Instant)`, ending up upon the same issue.

**Comment by kchibisov** [comment]
Don’t use sleep, use WaitUntil, and share the code you’ve used with WaitUntil. With sleep you block event processing entirely. Also mention what platform you are on.

In general, I was doing frame control with WaitUntil when I had to impelement it, and it worked with completely arbitrary fps (1fps, etc) https://git.sr.ht/~kchibisov/generations/tree/master/src/main.rs#L101 (this code won’t work, since it points to dead winit branch, so requires patching to point to winit master)

**Comment by arenacraftwow** [comment]
>Don’t use sleep

Sure, but just to be clear - in the code I gave `thread::sleep()` is meant to simulate a longer running operation like executing the game logic & re-rendering the screen.

>Also mention what platform you are on.

updated main post (info at the top of the top).

>use WaitUntil, and share the code you’ve used with WaitUntil

Well I lost the exact code so I will just try again and post it here. I will also take a look at your implementation, maybe this time I will get luckier.

**Comment by kchibisov** [comment]
Could you try drawing on `RedrawEventsCleared` instead of on every event, since you queue a lot of redraws and it could take a lot of time to process all of them? Right now if you move mouse you'll draw on each motion, which is just a lot.

**Comment by kchibisov** [comment]
I'll close this issue, since it's more of a user error, since you've decided to draw on each event, instead of once user events finished processing. There's a note in docs on `MainEventsCleared` that you should draw after it, since you've started redrawing stagehttps://docs.rs/winit/0.22.2/winit/event/enum.Event.html#variant.MainEventsCleared . You may also notice that all examples are drawing on `RedrawRequested`, though they are not asking for next redraw events.
