### ISSUE TITLE
How to draw at high frame rate?

### ISSUE THREAD

**Issue by lattice0** [rust-windowing/glutin#1330]
The only event I saw that gets close to a redraw request is

`glutin::event::Event::RedrawRequested(window_id)`

but this is only issued when the OS invalidates the window data or the application calls it. However calling the application isn't good because I don't know at which rate I can call it. It'd be better to get a call for each frame of the window and then issue the OpenGL drawing when this happens.

I'm writing a video renderer so it must play at the highest frame rate possible. How can I achieve that?

None of the window events match a pure redraw in the sense that it's called for every frame

**Comment by chrisduerr** [comment]
Just do it. What's stopping you from rendering at whatever framerate you want? There is no frames in glutin, you can render at whatever you want.

**Comment by lucaszanella** [comment]
@chrisduerr you mean

```
event_loop.run(move |event, _, control_flow| {
        *control_flow = match event {
            glutin::event::Event::WindowEvent { event, .. } => match event {
                // Break from the main loop when the window is closed.
                glutin::event::WindowEvent::CloseRequested => {
                    glutin::event_loop::ControlFlow::Exit
                }
                // Redraw the triangle when the window is resized.
                glutin::event::WindowEvent::Resized(..) => {
                    //self.draw();
                    glutin::event_loop::ControlFlow::Poll
                }
                
                _ => glutin::event_loop::ControlFlow::Poll,
            },
            _ => {
                //draw here
                glutin::event_loop::ControlFlow::Poll
            },
        };
    });
```
?

Drawing inside the event loop?

**Comment by chrisduerr** [comment]
It doesn't need to be inside the match arm at all. You can draw whenever you want. And request your own redraws whenever you want.

**Comment by lucaszanella** [comment]
@chrisduerr I've been thinking about this. In order to draw from another thread, I'd have to share some resources like `Display`, which do not implement `Sync`. Example: https://github.com/glium/glium/blob/master/examples/triangle.rs#L141 to call this closure from another thread I'd have to `Send + Sync` it. In my case it's even worse as I use `PixelBuffer`s. 

How am I suppose to draw from other threads?

**Comment by kchibisov** [comment]
glutin is all about context creation, it has very little to do with multi threading and glium, your question seems glium specific, not glutin one. With glutin it's pretty simple, since winit window is Send + Sync, so the only thing you'd need is to send data from event loop thread to renderer thread via some synchronization primitive, like channel or some other sharing mechanism.

That's some example pseudo code how you can do that, you can even ask for new frames on your thread 2, since you can pass `Window` to it.

```rust
// Thread 1
evlp.run_return() {
    // handle events

    tx.send_data(frame_data);
}

// Thread 2
while let Ok(data) = rx.recv() {
    draw(data);
}
```

**Comment by lucaszanella** [comment]
@kchibisov I still don't get it. On thread 2, you call draw. Let's suppose it's the draw function in the `triangle.rs` example: https://github.com/glium/glium/blob/84f82d3098fbc75aa22160b47bf0a2bdada01f07/examples/triangle.rs#L141

```
    let draw = move || {
        // building the uniforms
        let uniforms = uniform! {
            matrix: [
                [1.0, 0.0, 0.0, 0.0],
                [0.0, 1.0, 0.0, 0.0],
                [0.0, 0.0, 1.0, 0.0],
                [0.0, 0.0, 0.0, 1.0f32]
            ]
        };

        // drawing a frame
        let mut target = display.draw();
        target.clear_color(0.0, 0.0, 0.0, 0.0);
        target.draw(&vertex_buffer, &index_buffer, &program, &uniforms, &Default::default()).unwrap();
        target.finish().unwrap();
    };
```

To call this function from any thread, I'd have to share the things inside of it, like `vertex_buffer`, `index_buffer`, `program`, etc, which are not `Send+Sync` (in my case I even use `PixelBuffer`s). That's my main problem.

I asked this on glium but they asked me to ask on glutin

**Comment by kchibisov** [comment]
I have no clue how are you drawing, I'm talking about some generic draw function, not `gluim` draw function, I can't help with gluim, but can with glutin stuff and such things, since I've never used glium.

If you can't send glium's display, it's glium problem, I don't understand what are you expecting from glutin here.

**Comment by chrisduerr** [comment]
> How am I suppose to draw from other threads?

You're not supposed to.

**Comment by bschwind** [comment]
@lucaszanella In general you want to draw on the main thread, so it may be necessary to set up some sort of messaging scheme (MPSC channels or otherwise) to send "draw" commands to the main thread responsible for rendering.

You can still do OpenGL stuff on other threads though. Look up OpenGL shared contexts (I use it via glutin's [with_shared_lists](https://docs.rs/glutin/0.26.0/glutin/struct.ContextBuilder.html#method.with_shared_lists) function). As an example, I use headless shared contexts in other threads in order to do extra image processing.

**Comment by kchibisov** [comment]
Glutin has nothing to do with event loop, so it's up to you how to use it now.
