### ISSUE TITLE
Request redraw from different thread

### ISSUE THREAD

**Issue by huntiep** [rust-windowing/glutin#1335]
I have an application which does some processing in a separate thread on startup. I would like to be able to call request_redraw from this other thread but I was having difficulty sharing the window context between threads. How would I go about this?

**Comment by chrisduerr** [comment]
So I don't 100% remember this, but I think it goes something like this:

Sharing a `winit` window across threads works perfectly fine, since it is both `Sync` and `Send`. However an active graphics context cannot be shared across threads. So what you have to do instead is deactivate that graphics context, which makes it `Send`, then send it over to the other thread and then you're allowed to reactivate it.

**Comment by huntiep** [comment]
I see, so I created my window as before but now I call `ContextWrapper::split` and put the window behind a mutex. Now I can call `request_redraw` from my processing thread, but it doesn't seem to be doing anything. I would expect that each time I call it the event loop would run with a `RedrawRequested` event but instead it just sits there until there is some sort of input, which is effectively the same behavior as before.
Is this expected behavior?

**Comment by chrisduerr** [comment]
Can you try sending a user event to an event loop proxy, rather than using the `request_redraw` function?

**Comment by huntiep** [comment]
That works, thank you. Is that the intended way to do this or is it a bug that `request_redraw` wasn't working.

**Comment by chrisduerr** [comment]
It's a bug. https://github.com/rust-windowing/winit/issues/1755
