### ISSUE TITLE
Frame rate fluctuating when using ControlFlow::WaitUntil

### ISSUE THREAD

**Issue by BearWithTie** [rust-windowing/glutin#1336]
I am recently looking into glium and made some experiments.
Whenever I am using ControlFlow::WaitUntil, the frame rate is fluctuating and not at all capped as I would expect.
Since the event loop is part of glutin I am reporting it here.

As a simple example, I am using gliums [tutorial-01](https://github.com/glium/glium/blob/793da7d27649cf16106504ae72df89cab2c3754b/examples/tutorial-01.rs), which does nothing except clearing the screen each frame.
It already includes code which should limit the frame rate to 60fps using ControlFlow::WaitUntil and I added some lines to count and print the number of frames which actually have been drawn.

```rust
fn main() {
    #[allow(unused_imports)]
    use glium::{glutin, Surface};

    let event_loop = glutin::event_loop::EventLoop::new();
    let wb = glutin::window::WindowBuilder::new();
    let cb = glutin::ContextBuilder::new();
    let display = glium::Display::new(wb, cb, &event_loop).unwrap();
    
    let mut frames = 0;
    let mut start = std::time::Instant::now();
    event_loop.run(move |event, _, control_flow| {
        frames += 1;
        if start.elapsed().as_secs() >= 1 {
            println!("{:.0}", frames as f64 / start.elapsed().as_millis() as f64 * 1000.0);
            start = std::time::Instant::now();
            frames = 0;
        }

        let next_frame_time = std::time::Instant::now() +
            std::time::Duration::from_nanos(16_666_667);
        *control_flow = glutin::event_loop::ControlFlow::WaitUntil(next_frame_time);

        match event {
            glutin::event::Event::WindowEvent { event, .. } => match event {
                glutin::event::WindowEvent::CloseRequested => {
                    *control_flow = glutin::event_loop::ControlFlow::Exit;
                    return;
                },
                _ => return,
            },
            glutin::event::Event::NewEvents(cause) => match cause {
                glutin::event::StartCause::ResumeTimeReached { .. } => (),
                glutin::event::StartCause::Init => (),
                _ => return,
            },
            _ => return,
        }

        let mut target = display.draw();
        target.clear_color(0.0, 0.0, 1.0, 1.0);
        target.finish().unwrap();
    });
}
```

It doesn't matter if I run it in debug or release mode, my output looks like this.
Instead of the frame rate being capped to ~60fps, it's fluctuating between 99fps and 3699fps (sometimes even higher).
```
644
160
102
208
107
116
99
100
126
941
1657
1569
135
166
3544
3699
209
115
```

**Comment by chrisduerr** [comment]
`WaitUntil` will not return control flow until **either** a new event comes in **or** the time is up. So the only thing this would help with would be to not draw less frequently than 60 times, which it seems to do for you.

It's also important to point out that using WaitUntil is **not** a good way to set the framerate. It's extremely prone to miss your GPU timings and vblank interval since it does no synchronization with your display/gpu whatsoever. It's also not guaranteed to be exact, so you're very likely to see some small natural fluctuations. This means that while on one frame you might hit right before the vsync, on another you might hit right after.

**Comment by BearWithTie** [comment]
Thanks, seems I haven't read the documentation carefully enough and made some assumptions.

Is there any recommended way to control FPS?
I'm pretty new to this and am using sleep right now after handling all events, however [this issue](https://github.com/rust-windowing/glutin/issues/1325) seems to suggest to use `WaitUntil` rather than sleep, which doesn't make sense according to your explanation.

**Comment by chrisduerr** [comment]
It sounds like you just want a locked 60 FPS. The best choice for that is probably to just use `with_vsync(true)`.

**Comment by chrisduerr** [comment]
Also you should use `WaitUntil` over sleep, since sleeping will cause serious troubles. If the goal is just to get a rough ballpark framerate limitation is place, you can use `WaitUntil` to redraw at least every X ms and then check your current timestamp after each event to see if you actually need to redraw.

So say you store a `next_redraw = Instant::now() + Duration::from_secs(16)` after having drawn the last time, then you make sure you 100% wake up by that by setting that as the `WaitUntil` time of control flow whenever you get an event and as long as `Instant::now()` is still smaller than that `next_redraw`, you just keep looping with `WaitUntil`.

That way you're at least not blocking winit from doing its job. Is that the ideal solution? Far from it. But that would certainly work "okay".

**Comment by BearWithTie** [comment]
Thanks, totally makes sense to decouple the event loop from the frame rate instead of blocking it. I'll see what I can come up with.

**Comment by Johnrobmiller** [comment]
This is a terribly named variable, the name of this variable is the exact opposite of what it does. The name "wait until" tells the user that the next frame will wait until a specific time, but in fact, the exact opposite happens.

This is extremely misleading. You guys really should give this thing a better communicated name.

**Comment by notgull** [comment]
This has been changed in `winit` v0.29

**Comment by MarijnS95** [comment]
@Johnrobmiller this hasn't been an issue for a very long time since `glutin` completely decoupled from `winit` - or at least is not relevant for this repository. I'll this as off-topic.

**Comment by Johnrobmiller** [comment]
> @Johnrobmiller this hasn't been an issue for a very long time since `glutin` completely decoupled from `winit` - or at least is not relevant for this repository. I'll this as off-topic. Especially since your comment is nothing more than a useless derogatory comment towards maintainers with no constructive/technical body otherwise.

I called you out for naming that variable badly, and you are not mature enough to handle criticism.

**Comment by Johnrobmiller** [comment]
> comment

There wasn't even any derogetory language in that criticism, it was just saying something is bad. I think that you are probably just an emotionally unstable person who gets your feathers ruffled up too easily

**Comment by kchibisov** [comment]
How glutin has anything to do with all of that? If you think that something is badly named send a patch, I don't see a problem.

**Comment by Johnrobmiller** [comment]
> How glutin has anything to do with all of that? If you think that something is badly named send a patch, I don't see a problem.

Oh, I thought that WaitUntil was a glutin method. If not, then that is my mistake
