### ISSUE TITLE
OpenGL ES 1.1 context created by android-examples

### ISSUE THREAD

**Issue by zbx1425** [rust-windowing/glutin#1468]
I used the code in the android-examples branch, and it seems that an OpenGL ES 1.1 context is created.
I'm trying to use a context of a higher API version instead, the highest available if possible. I searched on the internet and cannot find instructions regarding glutin setups required to achieve that.
On the other hand, the example on desktop platform does give me the highest available API version.
Sorry for that I have poor understandings on the internals of glutin, and any help would be appreciated.
![image](https://user-images.githubusercontent.com/25097028/189521721-737a4d7b-9c3c-4c86-93d5-425116b056d9.png)

**Comment by kchibisov** [comment]
If you look at the context creation attributes you may find the `ContextAttributes`(use `cargo doc`) struct. And just by looking through it you may find that you can explicitly specify the version of the context you want.

https://github.com/rust-windowing/glutin/blob/24812ca627283b1d9189cd46d8a450eea108e68d/glutin/src/context.rs#L192

That's what you need here. Pass the version you need there. Like `Gles(3, 0)` or something like that.

**Comment by zbx1425** [comment]
Thanks for the speedy response! Missed that completely.
Though is there a way to utilize the highest available version on the system?
It seems that on Windows when `with_context_api` is not specified, the highest available version is used.

**Comment by kchibisov** [comment]
That's the behavior depending on the system, I guess. Since on Wayland + EGL it also picks the maximum value. I don't see any way to request the maximum value. Maybe the difference that we pick OpenGL and not ES on desktop platforms by default and ES does that.

In general you can pick some very big value and fallback to lower one on failure.

This is all platform defendant in the end, if we had a way to request a max we'd have that implemented...
