### ISSUE TITLE
Not Issue - I am having problems with Wayland/Nvidia and Glutin

### ISSUE THREAD

**Issue by Nazariglez** [rust-windowing/glutin#1544]
Hi Everybody, this is not an issue but a question. 

I am the maintainer of [notan](https://github.com/Nazariglez/notan) and we're having issues with wayland and nvidia after we updated to 0.30. This is the error: `[destroyed object]: error 7: failed to import supplied dmabufs: Unsupported buffer format 875713345`. You can read more [here](https://github.com/Nazariglez/notan/issues/187#issuecomment-1356843557). 

And this is the implementation of the last version of glutin for us: https://github.com/Nazariglez/notan/blob/develop/crates/notan_winit/src/gl_manager.rs

I am running out of ideas, so I thought I to ask here. It would be great if someone could give me some directions/hints about what it wrong. Does this error ring a bell for you?

Thanks for the help

**Comment by kchibisov** [comment]
It's likely that nvidia driver advertised the configuration it can't support, then you've used it and the compositor failed with it? Nvidia issues like that are up to nvidia, since there's no code I can look at to fix them nor I have nvidia hardware. I'd advise starting with the default config we're using and also providing the `WAYLAND_DEBUG=1` log showing that issue.

nvidia on Wayland is unstable and breaks very, very often...

**Comment by Nazariglez** [comment]
Hey @kchibisov thanks for the help at https://github.com/Nazariglez/notan/issues/187, I am closing the issue here! Thanks
