### ISSUE TITLE
Should upgrade winit to the latest version?

### ISSUE THREAD

**Issue by richerfu** [rust-windowing/glutin#1720]
It seems like that `winit` has some break changes after `0.30.0`. `glutin-winit` is using `0.30.0` now and should we upgrade `winit` to `0.30.7`?

**Comment by kchibisov** [comment]
what breaking changes are you talking about in particular? it's all patch compatible, you should be able to just update regardless.

**Comment by richerfu** [comment]
You're correct. To be more precise, the changes are derived from the master main branch of winit. For instance, 'window' has transitioned from `struct window` to `trait window`.

 However, it appears that these modifications aren't incorporated in some of the newly released versions.
If I intend to add support for additional platforms, which branch would you suggest I use? Master or 0.30.x?

**Comment by MarijnS95** [comment]
Those `winit` changes are breaking changes that can't be published as part of any `0.30.x` release per the definition of semver. They are all scheduled for the next breaking release of `winit` (i.e. `0.31.0`) but I don't think a strict release date has been set.

Your question regarding targeting `master` or `0.30.x` seems to be aimed at `winit` instead of `glutin`. `glutin` is already at version `0.32` and I don't think we're backporting anything to the older `0.30` release which goes paired with `winit 0.28` (also noting that `glutin` and `winit` release tracks are completely decoupled, only the `glutin-winit` crate ties them together).

If I had to guess, you're inquiring about #1702 being backported / targeted at the `glutin 0.32` branch instead so that it might make it into the next patch release?

**Comment by kchibisov** [comment]
>However, it appears that these modifications aren't incorporated in some of the newly released versions.
If I intend to add support for additional platforms, which branch would you suggest I use? Master or 0.30.x?

glutin doesn't depend on winit, and glutin-winit is just a glue, so you don't have to touch any of that code at all, unless you want to add something inside glutin directly, but again, all of that doesn't depend on winit.

**Comment by richerfu** [comment]
Actually, I'm attempting to adapt winit to some new platforms, and I'd like to use some example codes from glutin to conduct tests and ensure the thoroughness of the adaptation. However, part of the current code relies on glutin-winit, and thus on winit, so I'd like to confirm whether, for the adaptation of winit's new platforms, I should prioritize using the master branch of the winit repository or 0.30.x?

**Comment by kchibisov** [comment]
what platform are you talking about? Generally, use master.

**Comment by MarijnS95** [comment]
@richerfu that depends how backportable your changes are. If they are, I recommend developing them against the `0.30.x` branch of `winit` so that you can test with the latest `glutin-winit`, but still open a PR against the `master` branch of `winit` so that they changes will live ahead in the upcoming versions.

**Comment by MarijnS95** [comment]
In any case all these questions are targeting `winit`; I recommend _transferring_ this issue to the other repository. The fact that it affects your usage of `glutin` is only a side-effect.
