### ISSUE TITLE
iOS support roadmap

### ISSUE THREAD

**Issue by tomaka** [rust-windowing/glutin#29]
- [ ] Basic support
- [ ] Events

**Comment by cmr** [comment]
Will need to roughly do what SDL2 does here, which is write some ObjC classes (note: can do this dynamically, using https://github.com/SSheldon/rust-objc) that handle talking to UIKit.

**Comment by cmr** [comment]
I need this. I'm going to work on this after I finish gamepad support. I believe it will be straightforward, though tedious.

**Comment by tomaka** [comment]
\o/

**Comment by cjhowe** [comment]
I see there are already [pieces of this](https://github.com/tomaka/glutin/blob/master/src/api/ios/delegate.rs) in glutin, although currently building the iOS target fails. I intend to send a pull request to finish and fix the iOS build and add an iOS target to the Travis build.

**Comment by francesca64** [comment]
glutin currently doesn't even compile for iOS... I've rewritten it so that it at least runs (though I won't be able to make a PR until after the next winit release), but I haven't succeeded in actually rendering anything. I'm not sure if I'll get around to fixing that, since the iOS Simulator runs super slowly on my computer and it's just really annoying to work on.
